export const localWorkshops = [
    {
        _id: "81b0b3681cf6",
        title: "Flow Acrobatics - Dresden",
        address: "Bautzner Straße 107",
        info: "For all levels",
        startDate: "2020-06-20",
        endDate: "2020-06-21",
        priceLabel1: "One day: €",
        priceLabel2: "Both days: €",
        price1: 60,
        price2: 95,
    },
    {
        _id: "e0a6ebb7d138",
        title: "Flow Acrobatics - Hamburg",
        address: "Bautzner Straße 107",
        info: "For all levels",
        startDate: "2020-07-18",
        endDate: "2020-07-19",
        priceLabel1: "One day: €",
        priceLabel2: "Both days: €",
        price1: 60,
        price2: 95,
    },
    {
        _id: "b6641c1ed1f1",
        title: "Flow Acrobatics - Barcelona",
        address: "Carrer de Trafalgar 24",
        info: "For all levels",
        startDate: "2020-08-08",
        endDate: "2020-08-09",
        priceLabel1: "One day: €",
        priceLabel2: "Both days: €",
        price1: 60,
        price2: 95,
    },
];
